In [ ]:
import numpy as np
import random
State_space = np.random.randint(0, 8, (30, 8))

random_indices = np.random.choice(State_space.shape[0], size = 24, replace = False)
cr = State_space[random_indices, :]


for i in range(1, 24, 2):
  block_index = random.randint(0,8)
  child1 = np.append(cr[i][0 : block_index], cr[i-1][block_index : 8])
  child2 = np.append(cr[i-1][0:block_index], cr[i][block_index:8])

  child1 = child1.reshape(1, 8)
  child2 = child2.reshape(1, 8)

  State_space = np.append(State_space, child1, axis = 0)
  State_space = np.append(State_space, child2, axis = 0)

random_indices = np.random.choice(State_space.shape[0], size = 16, replace = False)
mu = State_space[random_indices, :]
# print(mu)
for i in range(0, 16):
  rand_index = random.randint(0, 7)
  rand_num = random.randint(0, 9)
  mu[i][rand_index] = rand_num


cost = np.zeros((54,1))
print(cost)
# cost = cost.reshape(54, 1)
# print(cost)
counter = 0
print(State_space)
for i in State_space:
  for j in range(0, 8):
    for k in range(j + 1, 8):
      if(i[j] == i[k]):
        cost[counter] += 1
      elif (i[j] - i[k] == j - k):
        cost[counter] += 1
  counter += 1

State_space = np.append(State_space, cost, axis = 1)



print(cost)
print(cost.shape)
print(State_space)
print()
State_space = State_space[np.argsort(State_space[:, 8])]
print(State_space)
State_space = np.delete(State_space, 8, axis = 1)
print(State_space)
State_space = State_space[0:20]
print(State_space)


[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
[[7 1 6 0 6 7 7 0]
 [4 4 7 0 6 6 5 0]
 [4 3 0 3 7 1 3 3]
 [3 4 7 6 0 3 3 1]
 [4 5 2 2 1 5 6 1]
 [0 6 1 4 6 5 4 6]
 [4 6 2 4 0 6 5 5]
 [3 7 6 7 1 4 3 6]
 [4 5 7 1 6 1 5 5]
 [0 7 5 0 7 4 0 3]
 [0 5 3 7 3 1 2 4]
 [2 4 2 7 6 5 6 3]
 [2 7 7 6 5 6 7 6]
 [4 1 4 3 4 5 7 0]
 [6 7 3 4 0 6 4 4]
 [5 3 4 1 1 2 0 3]
 [0 6 0 1 7 7 4 6]
 [4 5 0 6 5 0 1 2]
 [7 4 6 1 0 6 1 5]
 [4 0 1 3 7 1 3 1]
 [2 3 2 6 6 7 6 5]
 [7 3 5 6 3 1 2 1]
 [3 6 2 4 7 0 1 5]
 [5 7 7 5 3 2 6 6]
 [2 4 5 4 3 3 5 5]
 [2 4 0 5 0 5 7 6]
 [7 0 3 0 1 2 0 1]
 [3 6 7 5 7 2 7 7]
 [0 5 1 2 4 7 1 4]
 [2 3 2 0 2 2 6 2]
 [4 1 4 3 4 5 5 5]
 [2 4 5 4 3 3 7 0]
 [2 7 2 0 2 2 6 2]
 [2 3 7 6 5 6 7 6]
 [4 4 7 0 3 1 2 4]
 [0 5 3 7 

In [ ]:
arr = [0, 1, 2, 3, 2, 7, 8, 8, 3];
cost = np.zeros((9,))
# print(cost)
cost = cost.reshape(9, 1)
print("Duplicate elements in given array: ");
#Searches for duplicate element
for i in range(0, len(arr)):
    for j in range(i+1, len(arr)):
        if(arr[i] == arr[j]):
            cost[i] += 1

print(cost)

Duplicate elements in given array: 
[[0.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]]


In [ ]:
costarr = np.empty([0, 1])
print(costarr)

[]


In [ ]:
def costdef(x):

    counter = 0

    for j in range(0, 8):
      for k in range(j + 1, 8):
        if(x[j] == x[k]):
          cost[counter] += 1
        if (x[j] - x[k] == j - k):
          cost[counter] += 1
    print(cost)
    print(cost.shape)
    # return cost

costdef([1,2,8,1,7,3,7,5])

[[884.]
 [  3.]
 [  7.]
 [  6.]
 [  7.]
 [  6.]
 [  4.]
 [  6.]
 [  6.]
 [  5.]
 [  3.]
 [  6.]
 [  9.]
 [  9.]
 [  8.]
 [  4.]
 [  6.]
 [  6.]
 [  3.]
 [  5.]
 [ 11.]
 [  4.]
 [  2.]
 [  5.]
 [  8.]
 [  3.]
 [  8.]
 [  8.]
 [  4.]
 [ 13.]
 [ 12.]
 [  4.]
 [ 12.]
 [  8.]
 [  5.]
 [  5.]
 [  8.]
 [  6.]
 [  6.]
 [  4.]
 [  3.]
 [  5.]
 [  5.]
 [  4.]
 [  4.]
 [  7.]
 [  6.]
 [  2.]
 [ 11.]
 [  6.]
 [  4.]
 [  3.]
 [  4.]
 [  4.]]
(54, 1)
